# Generated by Django 3.2.10 on 2021-12-17 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-name',)},
        ),
        migrations.RemoveField(
            model_name='product',
            name='usability',
        ),
    ]
