# Generated by Django 3.2.10 on 2021-12-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20211217_1059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-usability',)},
        ),
        migrations.AddField(
            model_name='product',
            name='usability',
            field=models.CharField(default=3, max_length=10),
        ),
    ]
