# Generated by Django 3.2.10 on 2021-12-17 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20211217_1125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-name',)},
        ),
        migrations.RemoveField(
            model_name='product',
            name='usability',
        ),
    ]
