# Generated by Django 3.2.10 on 2021-12-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20211217_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='carbs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='energy_values',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fatty_substances',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='proteins',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
