# Generated by Django 3.2.10 on 2022-01-12 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('raison_sociale', models.TextField(blank=True, null=True)),
                ('siret', models.CharField(blank=True, max_length=255, null=True)),
                ('object', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devis', to='devis.status')),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
    ]
