# Generated by Django 3.2.10 on 2022-01-12 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Devis',
            new_name='Devi',
        ),
        migrations.RenameModel(
            old_name='Status',
            new_name='Statu',
        ),
    ]
