# Generated by Django 3.2.10 on 2022-01-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0002_auto_20220112_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='devi',
            name='category',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='devi',
            name='raison_sociale',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='devi',
            name='siret',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
