# Generated by Django 3.2.12 on 2022-03-08 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0007_devi_rida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devi',
            name='rida',
        ),
    ]
